# Generated by Django 3.2.3 on 2021-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True)),
                ('s_name', models.CharField(max_length=122)),
                ('r_id', models.IntegerField(unique=True)),
                ('r_name', models.CharField(max_length=122)),
                ('c_email', models.CharField(max_length=122)),
                ('c_balance', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('transaction', models.IntegerField()),
            ],
        ),
    ]
