# Generated by Django 3.2.3 on 2021-06-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_c_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_history',
            old_name='date',
            new_name='t_date',
        ),
        migrations.RemoveField(
            model_name='c_history',
            name='c_balance',
        ),
        migrations.RemoveField(
            model_name='c_history',
            name='c_email',
        ),
    ]
