# Generated by Django 3.2.3 on 2021-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20210610_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_history',
            name='r_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_history',
            name='s_id',
            field=models.IntegerField(),
        ),
    ]
